name: tahap2
description: "inventory menggunakan supabase"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: ['./assets/']
